### ISSUE TITLE
Metadata questions for Bob+Andy

### ISSUE THREAD

**Issue by atdyer** [FRF-Remote-Sensing/DuneLidar#9]
Here's part of the template file I've been working on for wave gauges:

```yaml
_variables:  ['time', 'z', 'lon', 'lat', 'frfX', 'frfY', 'spX', 'spY', 'hs', 'wl']
_attributes: []
_dimensions: ['time', 'z']

time:
    name: 'time'
    units: 'seconds since 1970-01-01 00:00:00'
    standard_name: 'time'
    long_name: 'UTC Sample Time'
    data_type: 'f8'
    dim: ['time']
    calendar: 'gregorian'
    fill_value: '-999.99'

z:
    name: 'water_surface_elevation'
    units: 'm'
    standard_name: 'water_surface_elevation'
    long_name: 'Water Surface Elevation'
    data_type: 'f8'
    dim: ['time']
    fill_value: '-999.99'
```

Some questions:
- What should go in ```_attributes```?
- Did I use ```dim``` correctly in the ```z``` block? It is essentially defining the x-axis to use when plotting z-values, correct?
- Are there any sort of naming conventions you are using for the ```name```, ```standard_name```, and ```long_name```? Where are these values being used/going to show up?
- Do we need to include coordinate systems other than lat/lon? We'll have calculated each gauge's location in the FRF coordinate system as well as state plane (see ```_variables```)
- Do time values always need to be in seconds since epoch?

**Comment by Bobfrat** [comment]
@atdyer  
* You shouldn't need anything in the _attributes section, not sure why I have that there, you can erase the whole line
* ```dim``` defines the variables dimensions as they will be stored in the NetCDF file. If ```z``` is a 1D timeseries variable then yes you are good here! For an example of 2 dimensions, CTD data collected over time at n depths might be in a variable of size (ntimes x ndepths). In that case you would define 2 dimensions, one for time (of size ntimes) and one for depth (of size ndepths).
* standard names are from the CF 1.6 convention. An xml file with all the standard names are [here](https://raw.githubusercontent.com/cf-convention/cf-convention.github.io/master/Data/cf-standard-names/16/src/cf-standard-name-table.xml). These are NOT mandatory so if you have a variable that doesn't have a matching standard name then you don't need to use one. ```name``` is arbitrary and will be the name of the variable found in the NetCDF file. We have been using a camelCase model. So ```water_surface_elevation``` would be ```waterSurfaceElevation```. ```long_name``` is just another descriptive name for the variable. If standard name isn't present then the Thredds Data Server will use this as the variable mapping name. More info [here](https://geo-ide.noaa.gov/wiki/index.php?title=NetCDF_Attribute_Convention_for_Dataset_Discovery) if you scroll about halfway down to the highly recommended variable attributes section.
* Lat/lon is the only mandatory geographic coordinate system and that's how we've been storing the other data. We can add a metadata field describing how to transform into FRF coordinates.
* Time does not need to be in seconds since epoch as long as you describe whatever units you are using in the units attributes of the time variable. To be consistent with the other data I suggest using it though. 

One other comment, for variables with the time dimension, be sure to add an attribute for coordinates:

``` coordinates: 'time lat lon' ```

**Comment by atdyer** [comment]
@Bobfrat 

Thanks so much, this helps a lot. Think I've pretty much got this nailed down, but I'll leave this open and ping you here if I run into any other issues.

**Comment by atdyer** [comment]
@Bobfrat 

Is it ```coordinates: 'time lat lon``` or ```coordinates: lat lon```? I've got an example file that shows it's the latter.

**Comment by Bobfrat** [comment]
@atdyer It should be ```time lat lon``` for all the time series variables. Sorry for the discrepancy!

**Comment by atdyer** [comment]
@Bobfrat 

For values like water level, where we'll have a minimum, maximum, and average value, is it okay to use the same standard_name for all three? E.g. each of those values using ```water_surface_height_above_reference_datum```

Also, when we provide values like water surface height above reference datum, do we need to somehow include the datum being used?

**Comment by Bobfrat** [comment]
@atdyer I would add the datum in the global attributes and the particular variable attributes too.
Just add ```datum: NAVD``` or whatever the datum is in the metadata.yml and something like this for the variable

```
measuredTide:
    name: 'waterLevelHeight'
    units: 'm'
    standard_name: 'water_surface_height_above_reference_datum'
    long_name: 'Water Level Height'
    data_type: 'f8'
    dim: ['time']
    fill_value: '-999.99'
    datum: 'NAVD'
    short_name: 'Height'
    coordinates: 'time lat lon'
```

Also, I would avoid using the same standard name for multiple variables.
